import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Fragment } from "react";
import Hero from "../components/UI/Hero";
import Services from "../components/UI/Services";
import About from "../components/UI/About";
import Portfolio from "../components/UI/Portfolio";
import Experience from "../components/UI/Experience";
import Contact from "../components/UI/Contact";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title> my portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/resume.png" />
      </Head>
      <Fragment>
      <Hero />
      <Services />
      <About />
      {/* <Portfolio /> */}
      <Experience />
      {/* <Contact /> */}
    </Fragment>
    </>
  )
}






